### PR TITLE
fix(tab-bar): notify value change event on pressing an arrow key

### LINKED ISSUE #395: [tab-bar] It is not possible to activate a tab using a keyboard
## Context

* Versions of browsers: Chrome 103
* OS: Windows 10
* Versions of Element Framework: 6.0.1

## Expected Behavior

It should be possible to activate a tab in `ef-tab-bar` by pressing Enter or Space on a keyboard.

## Current Behavior

It is not possible to activate a tab in `ef-tab-bar` with a keyboard.

## Steps to Reproduce

1. Open the first example at https://ui.refinitiv.com/elements/tab-bar (sorry, but I did not find how to make a permalink to the examples)
2. Focus the tab-bar by clicking on it or by using Tab key on a keyboard. 
3. Select any tab that is not currently active using arrows on a keyboard.
4. Press Enter/Space  

chrome_t3eAce2a8E

### LINKED ISSUE #396: [tab-bar] An active tab loses its active state when another tab is selected using a keyboard
## Context

* Versions of browsers Chrome 103
* OS: Windows 10
* Versions of Element Framework: 6.0.1

## Expected Behavior

A tab in a tab bar should remain active when a user navigates across tabs using a keyboard

## Current Behavior

A tab in a tab bar loses its active state when a user navigates across tabs using a keyboard

## Steps to Reproduce

1. Open the first example at https://ui.refinitiv.com/elements/tab-bar (sorry, but I did not find how to make a permalink to the examples)
2. Click the first tab to ensure it is active
3. Move the cursor out of tab-bar
4. Move to another tab by pressing the right arrow on a keyboard
5. Notice that the first tab is not highlighted as active and a click on it produces a `value-changed` event.
chrome_KekybPzPZT

### PR DESCRIPTION
**Pull request by Sarin-Udompanish**
## Description
`value-change` event is not fired when pressing an arrow key.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: packages/elements/src/tab-bar/index.ts [hunk 1]
```diff
@@ -94,15 +94,15 @@ export class TabBar extends BasicElement {
   @property({ type: String, attribute: false })
   public set value (value: string) {
     value = typeof value === 'string' ? value : String(value);
-    const oldValue = this._value;
+    const oldValue = this.oldValue;
     if (value !== oldValue && this.isValidValue(value)) {
-      this._value = value;
+      this.oldValue = value;
```
Comment (wsuwt) [inline packages/elements/src/tab-bar/index.ts]: You might not need `oldValue` property if you leave setter and getter to ControlElement where `this. activateTab` can be called during `willUpdate()` lifecycle.

File: packages/elements/src/tab-bar/index.ts [hunk 2]
```diff
@@ -84,7 +84,7 @@ export class TabBar extends BasicElement {
    * Internal value of tab bar.
    * Controlled by public setter and getter
    */
-  private _value = '';
+  private oldValue = '';
```
Comment (wsuwt) [inline packages/elements/src/tab-bar/index.ts]: You can now use `_value` instead of `oldValue` just to be more consistent.

**Review by wsuwt — APPROVED** [review]
